In [3]:
import numpy as np

In [4]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
print(ar)
ar

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

맨끝에 ar 또는 변수를 넣어주면 그 변수의 정의를 출력한다.

In [5]:
print(type(ar))

<class 'numpy.ndarray'>


In [6]:
data = [ 0,1,2,3,4,5,6,7,8,9]
data1 = list(range(10))
print(data)
print(data1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
answer = []
for di in data:
    answer.append(2*di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [15]:
x = np.array(data)
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [26]:
list_a = [1,2,3]
list_b = [10,20,30]
list_a = np.array([1,2,3])
list_b = np.array([10,20,30])
2*list_a + list_b

array([12, 24, 36])

In [24]:
a = np.array([2,2,2])
print(a)
a == 2

[2 2 2]


array([ True,  True,  True])

In [22]:
a = np.array([1,2,3])
print(b)
a > 10

[1 2 3]


array([False, False, False])

In [19]:
b = np.array([10,20,30])
print(b)
b > 10

[10 20 30]


array([False,  True,  True])

In [27]:
(a == 2) & (b > 10)
(a == 2) | (b > 10)

array([False,  True,  True])

In [ ]:
c = np.array([[0,1,2], [3,4,5]])
print(c)
c

행의 갯수 2차원의 요소갯수

In [30]:
len(c)

2

열의 갯수 1차원의 요소 갯수

In [33]:
print(c[0])
len(c[0])

[0 1 2]


3

In [34]:
x = np.array([[10,20,30,40],[50,60,70,80]])
print(x)
x

[[10 20 30 40]
 [50 60 70 80]]


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [38]:
y = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
print(y)
y

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [39]:
len(y), len(y[0]), len(y[0][0])

(2, 3, 4)

In [42]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


ndim속성은 배열의 차원(2차원인지 3차원인지) shape속성은 배열의 크기(2행 3열)를 반환한다.

In [43]:
y = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]])
print(y)
print(y.ndim)
print(y.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
3
(2, 3, 4)


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [46]:
y[0,0,:3]

array([1, 2, 3])

In [48]:
y[1,2]

7

In [51]:
m = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

In [52]:
m[-1,-1]

12

In [53]:
m[1,1:3]

array([7, 8])

In [55]:
[[m[0,2],m[0,3]],[m[1,3],m[2,0]]]

[[3, 4], [8, 9]]

In [57]:
m = np.array([[0,1,2,3,4],
               [5,6,7,8,9],
               [10,11,12,13,14]])

In [58]:
m[:2,-2:]

array([[3, 4],
       [8, 9]])

In [61]:
a = np.array([0,1,2,3,4,5])
idx = np.array([True, False, True, False, True, False])
a[idx]

array([0, 2, 4])

In [63]:
np.array([0,1,2])[np.array([True, False, True])]

array([0, 2])

In [64]:
print(a)
a % 2

[0 1 2 3 4 5]


array([0, 1, 0, 1, 0, 1], dtype=int32)

In [65]:
a % 2 == 0

array([ True, False,  True, False,  True, False])

In [66]:
a[a % 2 == 0]

array([0, 2, 4])

In [67]:
a = np.array([11,22,33,44,55,66,7,88,99])
idx = np.array([0,2,4,6,8])
a[idx]

array([11, 33, 55,  7, 99])

In [68]:
idx = np.array([0,0,0,0,0,1,1,1,1,1,2,2,2,2,2])
a[idx]

array([11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [69]:
a = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
a[:,[True, False, True, False]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [73]:
a[[2,0,1], :] #행의 순서 바꾸기

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [74]:
a[[2,0,1]]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [75]:
r = range(1,21)
x = np.array(r)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [83]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [85]:
x = np.array(range(1,21))
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [86]:
x[x % 4 ==1]

array([ 1,  5,  9, 13, 17])

In [88]:
x[(x % 3 ==1)&(x % 4 ==1)]

array([ 1, 13])

In [90]:
x = np.array([1.0,2.0,3.0])
x.dtype


dtype('float64')

In [91]:
y = np.array([1,2.0,3])
y.dtype

dtype('float64')

In [92]:
x = np.array([1,2,3], dtype='f')
x.dtype

dtype('float32')

In [93]:
x[0] + x[1]

3.0

In [97]:
x = np.array([1,2,3], dtype='U')
x.dtype, x

(dtype('<U1'), array(['1', '2', '3'], dtype='<U1'))

In [98]:
x[0] + x[1]

'12'

np.array([0,-1,0]) / np.array([1,0,0,0])

In [99]:
np.log(0)

<ipython-input-99-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [101]:
np.array([0,1,-1,0]) / np.array([1,0,0,0])

<ipython-input-101-720e9e2d83ea>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])
<ipython-input-101-720e9e2d83ea>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [102]:
np.log(0) #밀도가 e인 로그함수

<ipython-input-102-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [103]:
np.exp(-np.inf)

0.0

In [104]:
np.exp(1)

2.718281828459045

In [105]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [107]:
a = np.zeros((2,3)) # 튜플을 입력하면 다차원 배열도 생성
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [108]:
a = np.zeros((5,2), dtype="i") # dtpye을 명시하면 해당 자료형 원소를 가진 배열 생성
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [119]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [120]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCD'
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [112]:
e = np.ones((2,3,4), dtype="i8") #0이 아닌 1로 초기화된 배열을 생성하려면 ones
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [121]:
f = np.ones_like(e, dtype='f')
f

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [123]:
f = np.zeros_like(e)
f

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)

In [125]:
#배열의 크기가 커지면 초기화하는데 시간이 걸리기때문에 empty명령어로 배열만 생성한다.
g = np.empty((4,3))
g

array([[0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125]])

In [129]:
%%time
h = np.empty((10000,10000))

Wall time: 0 ns


In [130]:
%%time
h = np.ones((10000,10000))

Wall time: 142 ms


In [131]:
%%time
h = np.zeros((10000,10000))

Wall time: 52.9 ms


In [135]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [137]:
np.arange(-10,11,2)

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])

In [138]:
np.arange(7,-9,-3)

array([ 7,  4,  1, -2, -5, -8])

In [141]:
np.arange(1.7,10.8,1.5)

array([ 1.7,  3.2,  4.7,  6.2,  7.7,  9.2, 10.7])

In [142]:
# np.linspace(시작,끝,갯수,endpoint = True/False)
np.linspace(0, 100, 5, endpoint = False)

array([ 0., 20., 40., 60., 80.])