In [7]:
import numpy as np

# np.linspace(시작,끝,갯수,endpoint = True/False) 등분함
np.linspace(0, 100, 5, endpoint = False)

array([ 0., 20., 40., 60., 80.])

In [3]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [4]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
np.linspace(0, 10, 10, endpoint = True)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [9]:
np.logspace(1,4,4) 

array([   10.,   100.,  1000., 10000.])

In [10]:
np.logspace(0.1, 1.0, num=10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [11]:
np.logspace(0.1, 2.0, 20)

array([  1.25892541,   1.58489319,   1.99526231,   2.51188643,
         3.16227766,   3.98107171,   5.01187234,   6.30957344,
         7.94328235,  10.        ,  12.58925412,  15.84893192,
        19.95262315,  25.11886432,  31.6227766 ,  39.81071706,
        50.11872336,  63.09573445,  79.43282347, 100.        ])

In [12]:
10**0.1, 10**0.2, 10**0.3, 10**0.4, 10**0.5

(1.2589254117941673,
 1.5848931924611136,
 1.9952623149688795,
 2.51188643150958,
 3.1622776601683795)

In [13]:
10**np.logspace(0.1, 2.0, 20) #linspace로 

array([1.81520388e+001, 3.84497210e+001, 9.89150364e+001, 3.25002298e+002,
       1.45304030e+003, 9.57352125e+003, 1.02771415e+005, 2.03973358e+006,
       8.77571170e+007, 1.00000000e+010, 3.88377550e+012, 7.06206848e+015,
       8.96650406e+019, 1.31481399e+025, 4.19543118e+031, 6.46721137e+039,
       1.31438733e+050, 1.24662103e+063, 2.70909024e+079, 1.00000000e+100])

In [1]:
import matplotlib.pyplot as plt
plt.plot(np.linspace(0.1, 2.0, 20), np.logspace(0.02, 2.0, 20))

ModuleNotFoundError: No module named 'matplotlib'

In [17]:
a = np.array([[1,2,3],[4,5,6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [21]:
a.T   #T속성으로 행과 열을 바꾼다

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
a.T.shape

(3, 2)

In [22]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
b = np.arange(12).reshape(3,2,2)
b

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [25]:
print(b.ndim)
print(b.shape)

3
(3, 2, 2)


In [28]:
ar = a.reshape(3, -1) #사용하는 원소의 갯수가 정해져있기때문에 reshape로 -1을 넣으면 자동으로 숫자로 대체할수 있따.
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a.reshape(3,-1).shape

(3, 4)

In [30]:
b = a.reshape(2,2,-1)  
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

flatten과 ravel은 다차원배열을 1차원으로 펼칠때 사용

In [31]:
print(b)
b.flatten()

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [43]:
x3 = x.reshape(1,-1)
x3

array([[0, 1, 2, 3, 4, 5]])

In [35]:
x1 = x.reshape(1,6)
x1

array([[0, 1, 2, 3, 4, 5]])

In [37]:
x2 = x.reshape(6,1)
x2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [38]:
x.reshape(6,) == x.reshape(1, 6)

array([[ True,  True,  True,  True,  True,  True]])

In [39]:
x.reshape(6,) is x.reshape(1, 6)

False

In [40]:
x.reshape(2, 3) == x.reshape(3, 2)

<ipython-input-40-b0c84c66be73>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  x.reshape(2, 3) == x.reshape(3, 2)


False

In [47]:
np.arange(11,31).reshape(4,-1)

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [51]:
np.arange(3.3,-8.3,-0.5).reshape(4,-1)

array([[ 3.3,  2.8,  2.3,  1.8,  1.3,  0.8],
       [ 0.3, -0.2, -0.7, -1.2, -1.7, -2.2],
       [-2.7, -3.2, -3.7, -4.2, -4.7, -5.2],
       [-5.7, -6.2, -6.7, -7.2, -7.7, -8.2]])

In [65]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [67]:
np.hstack([a1,a2]) # vstack은 1차원요소를 합친다

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [60]:
a3 = np.arange(10,70,10).reshape(2,3)
a3

array([[10, 20, 30],
       [40, 50, 60]])

In [59]:
np.hstack([a1,a2,a3])

array([[ 1.,  1.,  1.,  0.,  0., 10., 20., 30.],
       [ 1.,  1.,  1.,  0.,  0., 40., 50., 60.]])

In [63]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
np.vstack([b1,b2])   # vstack은 2차원요소를 합친다

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
cs1 = np.array([1,2,3])
cs2 = np.array([10,20,30])
np.column_stack([cs1,cs2])  #동일 갯수의 array의 인덱스에 맞게 배열

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [77]:
c1 = np.ones(3)
print(c1)
print(c1.shape)
c1

[1. 1. 1.]
(3,)


array([1., 1., 1.])

In [70]:
c2 = np.zeros(3)
c2

array([0., 0., 0.])

In [71]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.]]])

In [72]:
c3 = np.ones((3,4))
c3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
c4 = np.zeros((3,4))
c4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
np.dstack([c3,c4]) #행열이 아닌 깊이 방향으로 배열한다.

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [75]:
(np.dstack([c1,c2])).shape

(1, 3, 2)

In [78]:
(np.dstack([c3,c4])).shape

(3, 4, 2)

In [107]:
a = np.linspace(10, 150, 15).reshape(3, -1)
a1 = np.ones((3,2))
a2 = np.zeros((3,3))
a3 = np.hstack([a2,a1])
np.vstack([a3,a,a3,a])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [111]:
a = np.arange(1,101).reshape(20,5)
b = np.arange(201,401,2).reshape(20,5)

np.savetxt('C:/Users/tiger/Desktop/Deeplearning/file_a.csv', a, fmt='%d', delimiter=',')
np.savetxt('C:/Users/tiger/Desktop/Deeplearning/file_b.txt', a+b, fmt='%d', delimiter=',')

In [112]:
read_a = np.loadtxt('C:/Users/tiger/Desktop/Deeplearning/file_a.csv', delimiter=",", skiprows=1, dtype='int')
read_a

array([[  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [113]:
read_b = np.loadtxt('C:/Users/tiger/Desktop/Deeplearning/file_b.txt', delimiter=",")
read_b

array([[202., 205., 208., 211., 214.],
       [217., 220., 223., 226., 229.],
       [232., 235., 238., 241., 244.],
       [247., 250., 253., 256., 259.],
       [262., 265., 268., 271., 274.],
       [277., 280., 283., 286., 289.],
       [292., 295., 298., 301., 304.],
       [307., 310., 313., 316., 319.],
       [322., 325., 328., 331., 334.],
       [337., 340., 343., 346., 349.],
       [352., 355., 358., 361., 364.],
       [367., 370., 373., 376., 379.],
       [382., 385., 388., 391., 394.],
       [397., 400., 403., 406., 409.],
       [412., 415., 418., 421., 424.],
       [427., 430., 433., 436., 439.],
       [442., 445., 448., 451., 454.],
       [457., 460., 463., 466., 469.],
       [472., 475., 478., 481., 484.],
       [487., 490., 493., 496., 499.]])