In [ ]:
import tensorflow.compat.v1 as tf  # 텐서플로우 버전1 사용, 버전2는 제외
tf.disable_v2_behavior()

a = tf.constant(7.0, name = 'data1')
b = tf.constant(3.0, name = 'data2')
c = tf.constant(2.0, name = 'data3')

v = a * b / c
print(v)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(v))

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.constant(5.0, name = 'a')
b = tf.constant(3.0, name = 'b')
c = tf.multiply(a,b, name = 'c')
d = tf.add(a,b, name = 'd')
e = tf.add(c,d, name = 'e')

sess = tf.Session()
print(sess.run(e))

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

tf.get_default_graph().get_operations()

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.constant(7.0, name = 'data1')
b = tf.constant(3.0, name = 'data2')
c = tf.constant(2.0, name = 'data3')

tf.get_default_graph().get_operations()

In [ ]:
print(a)

In [ ]:
print(a.op) # a의 오퍼레이션

In [ ]:
print(a.op.outputs) #a의 출력에 접근하여 a의 입력값 확인

In [ ]:
print(a is a.op.outputs[0])

In [ ]:
print(a.op.node_def.attr['value'].tensor.float_val[0]) #a의 오퍼레이션 프로토콜 버퍼에서 출력값을 확인해볼수있음

In [ ]:
v = a * b / c
tf.get_default_graph().get_operations()

In [ ]:
print('v.op.outputs=', v.op.outputs)

In [ ]:
print(v.op)

In [ ]:
print(v.op.inputs[0])
print(v.op.inputs[1])

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.constant(5.0, name = 'a')
b = tf.constant(3.0, name = 'b')
c = tf.multiply(a,b, name = 'c')
d = tf.add(a,b, name = 'd')
e = tf.add(c,d, name = 'e')
    
sess = tf.Session()
outs = sess.run(e)
sess.close()
print("outs =", outs)


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

hello = tf.constant("Hello, Tensorflow!")
sess = tf.Session()

print(sess.run(hello))

sess.close()

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

input_Data = [1,2,3,4,5]

x = tf.placeholder(dtype=tf.float32)
y = x * 2

sess = tf.Session()
result = sess.run(y, feed_dict={x:input_Data})
print(result)

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

p_holder1 = tf.placeholder(dtype=tf.float32)
p_holder2 = tf.placeholder(dtype=tf.float32)
p_holder3 = tf.placeholder(dtype=tf.float32)
val1 = 5
val2 = 10
val3 = 3

ret_val = p_holder1 * p_holder2 + p_holder3

sess = tf.Session()
feed_dict_data = {p_holder1 : val1, p_holder2 : val2, p_holder3 : val3,}
result = sess.run(ret_val, feed_dict=feed_dict_data)
sess.close()
print(result)

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

I = tf.placeholder(tf.float32, [2,4])
i = [[1,2,3,4],[5,6,7,8]]

W = tf.placeholder(tf.float32, [4,2])
w= [[1,1],[2,2],[3,3],[4,4]]

m_cal = tf.matmul(I,W)

sess = tf.Session()
result = sess.run(m_cal, feed_dict={I:i, W:w})
sess.close()

print(result)


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

I = tf.Variable([[1,2,3,4],[5,6,7,8]], tf.float32)
W = tf.Variable([[1,1],[2,2],[3,3],[4,4]], tf.float32)

m_cal = tf.matmul(I,W)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(sess.run(m_cal))
sess.close()

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

input_Data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
W = tf.Variable([2], dtype=tf.float32)
y = W * x

sess = tf.Session()

init = tf.global_variables_initializer()
sess.run(init)

result = sess.run(y, feed_dict={x:input_Data})
print(result)

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x = tf.Variable(5, dtype=tf.int32)
print(x)

z = tf.assign(x, 7) # tf.global_variables_initializer() 과 같음

sess = tf.Session()
sess.run(z)
y = sess.run(x)
print(y)
sess.close()

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x = tf.Variable(tf.zeros((2,2)), dtype=tf.float32)

y = tf.Variable([[1,2], [3,4]], dtype=tf.float32)
x = tf.assign(x, y) # y값을 x로 넣어주고 이니셜라이징해줘도

sess = tf.Session()

z = tf.global_variables_initializer() # y를 또 이니셜라이징해줘야 실행됨

sess.run(z)
k = sess.run(x)
print(k)
sess.close()

In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

mat_mg = [1,2,3,4,5]
label = [10,20,30,40,50]
ph_img = tf.placeholder(dtype=tf.float32)
ph_lb = tf.placeholder(dtype=tf.float32)

ret_tensor = ph_img + ph_lb

sess = tf.Session()
feed_dict_data = {ph_img : mat_mg, ph_lb : label}
result = sess.run(ret_tensor, feed_dict=feed_dict_data)
sess.close()
print(result)

[11. 22. 33. 44. 55.]


In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

input_data = [[1.,2.,3.],[1.,2.,3.],[2.,3.,4.]]
x = tf.placeholder(dtype=tf.float32, shape=[None,3])
w = tf.Variable([[2.,], [2.,], [2.,]], dtype=tf.float32)
y = tf.matmul(x,w)
sess = tf.Session()

init = tf.global_variables_initializer()
sess.run(init)

result = sess.run(y, feed_dict={x:input_data})
print(result)

[[12.]
 [12.]
 [18.]]


In [5]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

input_data = [[1,1,1],[2,2,2]]
x = tf.placeholder(dtype=tf.float32, shape=[2,3])
w = tf.Variable([[2], [2], [2]], dtype=tf.float32)
b = tf.Variable([4],dtype=tf.float32)

y = tf.matmul(x,w) + b # 브로드캐스팅으로 1*1행렬을 더하는 대상에 맞게 2*1행렬로 자동으로 stretch한다. 줄이는건 불가능
print(x.get_shape())

sess = tf.Session()

init = tf.global_variables_initializer()
sess.run(init)

result = sess.run(y, feed_dict={x:input_data})
print(result)

(2, 3)
[[10.]
 [16.]]


In [6]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
a = tf.constant([[1.,2.,3.]])
b = tf.constant([[2.0],[2.0],[2.0]])
y = tf.matmul(a,b)
print(a.get_shape())
print(b.get_shape())
print(y.get_shape())
print(y)

sess = tf.Session()

init = tf.global_variables_initializer()
sess.run(init)

result = sess.run(y)
print(result)

(1, 3)
(3, 1)
(1, 1)
Tensor("MatMul_2:0", shape=(1, 1), dtype=float32)
[[12.]]
