In [6]:
###############################
# 영상 파일 16비트 32비트 읽기

import cv2
from Common.utils import print_matInfo

title1, title2 = '16bit unchanged','32bit unchanged'
color2unchanged1 = cv2.imread('images/read_16.tif', cv2.IMREAD_UNCHANGED)
color2unchanged2 = cv2.imread('images/read_32.tif', cv2.IMREAD_UNCHANGED)

if color2unchanged1 is None or color2unchanged2 is None :
    raise Exception("영상 읽기에러")
    
print('16/32비트 영상행렬 좌표(10,10) 화소값')

print(title1, "원소 자료형", type(color2unchanged1[10][10][0]))
print(title1, "화소값(3원소)", color2unchanged1[10, 10])
print(title2, "원소 자료형", type(color2unchanged2[10][10][0]))
print(title2, "화소값(3원소)", color2unchanged2[10, 10])
print()

print_matInfo(title1, color2unchanged1)
print_matInfo(title2, color2unchanged2)
cv2.imshow(title1, color2unchanged1)
cv2.imshow(title2, (color2unchanged2*255).astype("uint8"))
cv2.waitKey(0)  

16/32비트 영상행렬 좌표(10,10) 화소값
16bit unchanged 원소 자료형 <class 'numpy.uint16'>
16bit unchanged 화소값(3원소) [48573 34438 23387]
32bit unchanged 원소 자료형 <class 'numpy.uint16'>
32bit unchanged 화소값(3원소) [59367 48830 35980]

16bit unchanged: depth(uint16), channels(3) -> mat_type(CV_16UC3)
32bit unchanged: depth(uint16), channels(3) -> mat_type(CV_16UC3)


-1

In [10]:
###############################
#  행렬을 영상파일로 저장

import cv2
from Common.utils import print_matInfo

image = cv2.imread('images/read_color.jpg', cv2.IMREAD_UNCHANGED)
if image is None : raise Exception("영상 읽기에러")
    
params_jpg = (cv2.IMWRITE_JPEG_QUALITY, 10)
params_png = (cv2.IMWRITE_PNG_COMPRESSION, 9)

cv2.imwrite('images/write_test1.jpg', image)
cv2.imwrite('images/write_test2.jpg', image, params_jpg)
cv2.imwrite('images/write_test3.jpg', image, params_png)
cv2.imwrite('images/write_test4.jpg', image)
print("저장완료")

저장완료


In [17]:
###############################
#  기본 배열 처리 함수

import cv2

image = cv2.imread('images/flip_test.jpg', cv2.IMREAD_COLOR)
if image is None : raise Exception("영상 읽기에러")

x_axis = cv2.flip(image, 0)
y_axis = cv2.flip(image, 1)
xy_axis = cv2.flip(image, -1)
rep_image = cv2.repeat(image, 1, 2)
trans_image = cv2.transpose(image)
trans_image2 = cv2.transpose(image, 0)

titles = ['image', 'x_axis', 'y_axis', 'rep_image', 'trans_image', 'trans_image2']
for title in titles :
    cv2.imshow(title, eval(title))   # 문자열을 명령어로 만듬
cv2.waitKey(0)

-1

In [19]:
###############################
#  채널 처리 함수
import numpy as np
import cv2

# 배열로 단일채널 3개 생성
ch0 = np.zeros((2,4), np.uint8) + 10 # 0원소 선언 후 10더하기
ch1 = np.ones((2,4), np.uint8) * 20 # 1원소 선언 후 20 곱하기
ch2 = np.zeros((2,4), np.uint8); ch2[:] = 30 # 0원소 선언 후 행렬원소 값 30지정

list_bgr = [ch0, ch1, ch2] # 단일 채널 모아서 리스트구성
merge_bgr = cv2.merge(list_bgr) # 채널 합성
split_bgr = cv2.split(merge_bgr) # 채널 분리 : 컬러영상 

print('split_bgr 행렬형태', np.array(split_bgr).shape)
print('merge_bgr 행렬형태', merge_bgr.shape)

print("[ch0] = \n%s" % ch0)
print("[ch1] = \n%s" % ch1)
print("[ch2] = \n%s" % ch2)
print("[merge_bgr] = \n%s" % merge_bgr)

print("[split_bgr[0]] = \n%s" %split_bgr[0])
print("[split_bgr[1]] = \n%s" %split_bgr[1])
print("[split_bgr[2]] = \n%s" %split_bgr[2])

split_bgr 행렬형태 (3, 2, 4)
merge_bgr 행렬형태 (2, 4, 3)
[ch0] = 
[[10 10 10 10]
 [10 10 10 10]]
[ch1] = 
[[20 20 20 20]
 [20 20 20 20]]
[ch2] = 
[[30 30 30 30]
 [30 30 30 30]]
[merge_bgr] = 
[[[10 20 30]
  [10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]
  [10 20 30]]]
[split_bgr[0]] = 
[[10 10 10 10]
 [10 10 10 10]]
[split_bgr[1]] = 
[[20 20 20 20]
 [20 20 20 20]]
[split_bgr[2]] = 
[[30 30 30 30]
 [30 30 30 30]]


In [22]:
###############################
#  영상 채널 분리

import numpy as np
import cv2

image = cv2.imread('images/color.jpg', cv2.IMREAD_COLOR)
if image is None : raise Exception("영상 읽기 에러")
if image.ndim != 3 : raise Exception("컬러 영상 아님")
    
bgr = cv2.split(image)
print("bgr 자료형", type(bgr), type(bgr[0]), type(bgr[0][0][0]))
print("bgr 원소개수", len(bgr))

cv2.imshow('image', image)
cv2.imshow('Blue channel', bgr[0])
cv2.imshow('Green channel', bgr[1])
cv2.imshow('Red channel', bgr[2])
cv2.waitKey()
cv2.destroyAllWindows()

bgr 자료형 <class 'list'> <class 'numpy.ndarray'> <class 'numpy.uint8'>
bgr 원소개수 3


In [26]:
###############################
#  사칙연산

import numpy as np,cv2

m1 = np.full((3,6), 10, np.uint8)
m2 = np.full((3,6), 50, np.uint8)
m_mask = np.zeros(m1.shape, np.uint8)
m_mask[:, 3:] = 1

m_add1 = cv2.add(m1, m2)
m_add2 = cv2.add(m1, m2, mask=m_mask)

m_div1 = cv2.divide(m1,m2)
m1 = m1.astype(np.float32)
m2 = np.float32(m2)
m_div2 = cv2.divide(m1,m2)

titles = ['m1','m2','m_mask','m_add1','m_add2','m_div1','m_div2']
for title in titles:
    print("[%s] = \n%s \n"%(title, eval(title))) # eval은 안의 문자나 변수를 바로 실행한다.


[m1] = 
[[10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]] 

[m2] = 
[[50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]] 

[m_mask] = 
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]] 

[m_add1] = 
[[60 60 60 60 60 60]
 [60 60 60 60 60 60]
 [60 60 60 60 60 60]] 

[m_add2] = 
[[ 0  0  0 60 60 60]
 [ 0  0  0 60 60 60]
 [ 0  0  0 60 60 60]] 

[m_div1] = 
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]] 

[m_div2] = 
[[0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2]] 



In [1]:
###############################
#  연산 함수2

import numpy as np,cv2

image1 = np.zeros((300,300), np.uint8)
image2 = image1.copy()

h, w = image1.shape[:2]
cx, cy = w//2, h//2
cv2.circle(image1, (cx, cy), 100, 255, -1) # -1은 내부채움
cv2.rectangle(image2, (0,0,cx, h), 255, -1)

image3 = cv2.bitwise_or(image1, image2)
image4 = cv2.bitwise_and(image1, image2)
image5 = cv2.bitwise_xor(image1, image2)
image6 = cv2.bitwise_not(image1)

cv2.imshow('image1', image1)
cv2.imshow('image2', image2)
cv2.imshow('bitwise_or', image3)
cv2.imshow('bitwise_and', image4)
cv2.imshow('bitwise_xor', image5)
cv2.imshow('bitwise_not', image6)
cv2.waitKey()


-1