In [1]:
import pandas as pd

In [3]:
s = pd.Series([9904312,3448737,2890451,2466052], index = ['서울','부산','인천','대구'])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [4]:
s.ndim

1

In [5]:
s.shape

(4,)

In [6]:
pd.Series(range(10,14)) #인덱스를 지정하지않으면 0부터 시작하는 인덱스 생성

0    10
1    11
2    12
3    13
dtype: int64

In [7]:
# 시리즈 인덱스는 index속성으로 접근할수 있다. 1차원 배열
s.index 

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [8]:
type(s.index)

pandas.core.indexes.base.Index

In [9]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [10]:
type(s.values)

numpy.ndarray

In [11]:
s.name = '인구'
s.index.name = '도시'
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [12]:
# numpt scalar 연산과 동일
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

In [14]:
s[1]

3448737

In [15]:
s[3],s['대구']

(2466052, 2466052)

In [16]:
s['부산']

3448737

In [17]:
s[[0,3,1]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [18]:
s[['서울','대구','부산']]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [20]:
(250e4 < s) & ( s< 500e4)

도시
서울    False
부산     True
인천     True
대구    False
Name: 인구, dtype: bool

In [21]:
s[(250e4 < s) & ( s< 500e4)]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [27]:
1e3

1000.0

In [28]:
s[1:3]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [29]:
s['부산' : '대구']

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [30]:
s0 = pd.Series(range(3), index = ['a','b','cc'])

In [31]:
s0

a     0
b     1
cc    2
dtype: int64

In [32]:
s0.a

0

In [33]:
s0.b

1

In [34]:
s0.cc

2

In [35]:
s0['a']

0

In [37]:
'서울' in s

True

In [38]:
'대전' in s

False

In [39]:
for a in s.items():
    print(a)

('서울', 9904312)
('부산', 3448737)
('인천', 2890451)
('대구', 2466052)


In [40]:
for k, v in s.items():
    print("%s = %d"%(k,v))

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [41]:
s.items

<bound method Series.items of 도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64>

In [43]:
s2 = pd.Series({'서울' : 9631482, '부산' : 3393191, '인천' : 2632035, '대전' : 1490195})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490195
dtype: int64

In [44]:
s2.name = '우리나라', s2.index.name = '도시'

In [46]:
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490195
Name: 우리나라, dtype: int64

In [47]:
s2.index

Index(['서울', '부산', '인천', '대전'], dtype='object')

In [50]:
# 키값이 같은것끼리 연산
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [55]:
s2 = pd.Series({'서울' : 9631482, '부산' : 3393191, '인천' : 2632035, '대전' : 1490195}, index = ['부산','서울','인천','대전'])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490195
dtype: int64

In [56]:
s.values - s2.values

array([ 6511121, -6182745,   258416,   975857], dtype=int64)

In [57]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [61]:
print(type(ds[ds.notnull()]))
rs = ds[ds.notnull()]
rs

<class 'pandas.core.series.Series'>


부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [62]:
rs['부산'] = 1.63
rs

부산         1.63
서울    272830.00
인천    258416.00
dtype: float64

In [63]:
rs['대구'] = 1.41
rs

부산         1.63
서울    272830.00
인천    258416.00
대구         1.41
dtype: float64

In [64]:
del rs['서울']
rs

부산         1.63
인천    258416.00
대구         1.41
dtype: float64

In [78]:
s = pd.Series([1,2,3,4], index = ['상','상','중','하'])
s2 = pd.Series([5,6,7,8], index = ['하','상','상','미'])
s + s2

미    NaN
상    7.0
상    8.0
상    8.0
상    9.0
중    NaN
하    9.0
dtype: float64

In [79]:
s - s2

미    NaN
상   -5.0
상   -6.0
상   -4.0
상   -5.0
중    NaN
하   -1.0
dtype: float64

In [91]:
data = {
    '2015' : [9904312,3448737,2890451,2466052],
    '2010' : [9631482, 3393191, 2632035, 2431774],
    '2005' : [9762546, 3512574, 2517680, 2456016], 
    '2000' : [9853972, 3655437, 2466338, 2473990],
    '지역' : ['수도권',' 경상권','수도권',' 경상권'],
    '2010-2015증가율' : [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ['지역', '2015','2010','2005','2000','2010-2015증가율']
index = ['서울','부산','인천','대구']

df = pd.DataFrame(data, index = index, columns = columns)
print(df)
df

      지역     2015     2010     2005     2000  2010-2015증가율
서울   수도권  9904312  9631482  9762546  9853972        0.0283
부산   경상권  3448737  3393191  3512574  3655437        0.0163
인천   수도권  2890451  2632035  2517680  2466338        0.0982
대구   경상권  2466052  2431774  2456016  2473990        0.0141


지역     2015     2010     2005     2000  2010-2015증가율
서울   수도권  9904312  9631482  9762546  9853972        0.0283
부산   경상권  3448737  3393191  3512574  3655437        0.0163
인천   수도권  2890451  2632035  2517680  2466338        0.0982
대구   경상권  2466052  2431774  2456016  2473990        0.0141

In [92]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       [' 경상권', 3448737, 3393191, 3512574, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       [' 경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [86]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015증가율'], dtype='object')

In [87]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [90]:
df.index.name = '도시'
df.columns.name = '특성'
df.name = '도시별 인구'
print(df)
df

특성    지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                         
서울   수도권  9904312  9631482  9762546  9853972         0.0283
부산   경상권  3448737  3393191  3512574  3655437         0.0163
인천   수도권  2890451  2632035  2517680  2466338         0.0982
대구   경상권  2466052  2431774  2456016  2473990         0.0141


특성    지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                         
서울   수도권  9904312  9631482  9762546  9853972         0.0283
부산   경상권  3448737  3393191  3512574  3655437         0.0163
인천   수도권  2890451  2632035  2517680  2466338         0.0982
대구   경상권  2466052  2431774  2456016  2473990         0.0141

In [93]:
df['2010-2015증가율'] = df['2010-2015증가율']*100
df

지역     2015     2010     2005     2000  2010-2015증가율
서울   수도권  9904312  9631482  9762546  9853972          2.83
부산   경상권  3448737  3393191  3512574  3655437          1.63
인천   수도권  2890451  2632035  2517680  2466338          9.82
대구   경상권  2466052  2431774  2456016  2473990          1.41

In [94]:
df['2010-2015증가율'] = ((df['2010'] - df['2005']) / df['2005']*100).round(2)
df

지역     2015     2010     2005     2000  2010-2015증가율
서울   수도권  9904312  9631482  9762546  9853972         -1.34
부산   경상권  3448737  3393191  3512574  3655437         -3.40
인천   수도권  2890451  2632035  2517680  2466338          4.54
대구   경상권  2466052  2431774  2456016  2473990         -0.99

In [95]:
del df['2010-2015증가율']
df

지역     2015     2010     2005     2000
서울   수도권  9904312  9631482  9762546  9853972
부산   경상권  3448737  3393191  3512574  3655437
인천   수도권  2890451  2632035  2517680  2466338
대구   경상권  2466052  2431774  2456016  2473990

In [99]:
print(df['2015'].shape)
df[['2010','2015']]

(4,)


2010     2015
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [97]:
print(df[['2010']].shape)
df[['2010']]

(4, 1)


2010
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [103]:
# 문자열은 숫자형 인덱스를 사용할수 없다. 그래서 try + Except를 사용한다.
try:
    df[0]
except Exception as e:
    print(type(e))

<class 'KeyError'>


In [105]:
import numpy as np
df2 = pd.DataFrame(np.arange(12).reshape(3,-1))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [113]:
np_array = np.arange(12).reshape(3,4)
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
np_array[:,2].reshape(3,1)

array([[ 2],
       [ 6],
       [10]])

In [108]:
df2[[1,2]]

1   2
0  1   2
1  5   6
2  9  10

In [109]:
np_array[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [114]:
df[2:]

지역     2015     2010     2005     2000
인천   수도권  2890451  2632035  2517680  2466338
대구   경상권  2466052  2431774  2456016  2473990

In [115]:
df[:1]

지역     2015     2010     2005     2000
서울  수도권  9904312  9631482  9762546  9853972

In [116]:
df[1:2]

지역     2015     2010     2005     2000
부산   경상권  3448737  3393191  3512574  3655437

In [117]:
df[1:3]

지역     2015     2010     2005     2000
부산   경상권  3448737  3393191  3512574  3655437
인천   수도권  2890451  2632035  2517680  2466338

In [118]:
df['2015']

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 2015, dtype: int64

In [119]:
df['2015'][1:3]

부산    3448737
인천    2890451
Name: 2015, dtype: int64