In [5]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [6]:
text = '해보지 않으면 해낼 수 없다.'

result = text_to_word_sequence(text)
print("\n원문: \n", text)
print("\n토큰화: \n", result)


원문: 
 해보지 않으면 해낼 수 없다.

토큰화: 
 ['해보지', '않으면', '해낼', '수', '없다']


In [8]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Flatten, Embedding


In [9]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.'
       '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.'
       '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.']

token = Tokenizer()
token.fit_on_texts(docs)

print("\n단어 카운트: \n", token.document_count)
print("\n각단어가 몇개의 문장에 포함되어 있는가 : \n", token.word_docs)
print("\n각 단어에 매겨진 인덱스 값: \n", token.word_index)



단어 카운트: 
 1

각단어가 몇개의 문장에 포함되어 있는가 : 
 defaultdict(<class 'int'>, {'토큰화': 1, '수': 1, '할': 1, '결과는': 1, '나누어': 1, '각': 1, '있습니다': 1, '한': 1, '먼저': 1, '해야': 1, '단어를': 1, '인식됩니다': 1, '텍스트의': 1, '합니다': 1, '딥러닝에서': 1, '단어로': 1, '사용': 1})

각 단어에 매겨진 인덱스 값: 
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용': 14, '할': 15, '수': 16, '있습니다': 17}


In [11]:
text = "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다."

#토큰화
token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [12]:
x = token.texts_to_sequences([text])
print("\텍스트, 토큰화 결과: \n", x)

\텍스트, 토큰화 결과: 
 [[1, 2, 3, 4, 5, 6]]


In [13]:
from tensorflow.keras.utils import to_categorical

word_size = len(token.word_index)+1

x= to_categorical(x, num_classes=word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [16]:
from numpy import array

docs = ['너무 재밌네요','최고예요','참 잘 만든영화에요','추천하고 싶은 영화입니다.','한번 더 보고 싶네요','글쎄요','별로에요',
       '생각보다 지루하네요','연기가 어색해요','재미없어요']

classes = array([1,1,1,1,1,0,0,0,0,0])

from tensorflow.keras.preprocessing.text import Tokenizer

token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)
x = token.texts_to_sequences(docs)
print("\텍스트, 토큰화 결과: \n", x)

from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_x = pad_sequences(x, 4)
print("\패딩 결과: \n", padded_x)

print("\n딥러닝 모델 시작 :")

from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Flatten, Embedding



{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든영화에요': 6, '추천하고': 7, '싶은': 8, '영화입니다': 9, '한번': 10, '더': 11, '보고': 12, '싶네요': 13, '글쎄요': 14, '별로에요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}
\텍스트, 토큰화 결과: 
 [[1, 2], [3], [4, 5, 6], [7, 8, 9], [10, 11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]
\패딩 결과: 
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 0  4  5  6]
 [ 0  7  8  9]
 [10 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]

딥러닝 모델 시작 :


In [19]:
from tensorflow.keras.preprocessing.text import Tokenizer

text = " I am a boy. My name is David"

token = Tokenizer(
    num_words=None,
    filters='!"#$%%()*+,-/:;<=>?@[\\]^_{|}~\t\n',
    lower=False,
    split=' ',
    char_level=False,
    oov_token=None,
    document_count=0,)
token.fit_on_texts([text])
print(token.word_index)

{'I': 1, 'am': 2, 'a': 3, 'boy.': 4, 'My': 5, 'name': 6, 'is': 7, 'David': 8}


In [44]:
from tensorflow.keras.preprocessing.text import Tokenizer

samples = ['The cat sat on the mat.','The dog ate my homework']

token_index = {}
for sample in samples:
    for word in sample.replace('.',' ').split():
        if word not in token_index:
            token_index[word] = len(token_index) + 1

print(token_index)


{'The': 1, 'cat': 2, 'sat': 3, 'on': 4, 'the': 5, 'mat': 6, 'dog': 7, 'ate': 8, 'my': 9, 'homework': 10}


In [45]:
import numpy as np
max_length = 10
results = np.zeros((len(samples), max_length, max(token_index.values()) + 1))
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.replace('.',' ').split()))[:max_length]:
        index = token_index.get(word)
        results[i,j,index] = 1

results 

array([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0