In [31]:
##############################
# 광물초음파 예측
################################
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras import optimizers # lr 조정할때 쓰임
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
np.random.seed(0)
tf.random.set_seed(0)

df = pd.read_csv('sonar.csv', header=None)
df.describe()

0           1           2           3           4           5   \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570   
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025   
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150   
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               6           7           8           9   ...          50  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000   
mean     0.121747    0.134799    0.178003    0.208259  ...    0.016069   
std      0.061788    0.085152    0.118387    0.134416  ...    0.012008   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080900    0.080425    0.097025    0.111275  ...    0.008425   
50%      0.106950    0.112100    0.152250    0.182400  ...    0.013900   
75%      0.154000    0.169600    0.233425    0.268700  ...    0.020825   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

               51          52          53          54          55          56  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.013420    0.010709    0.010941    0.009290    0.008222    0.007820   
std      0.009634    0.007060    0.007301    0.007088    0.005736    0.005785   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007275    0.005075    0.005375    0.004150    0.004400    0.003700   
50%      0.011400    0.009550    0.009300    0.007500    0.006850    0.005950   
75%      0.016725    0.014900    0.014500    0.012100    0.010575    0.010425   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

               57          58          59  
count  208.000000  208.000000  208.000000  
mean     0.007949    0.007941    0.006507  
std      0.006470    0.006181    0.005031  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003675    0.003100  
50%      0.005800    0.006400    0.005300  
75%      0.010350    0.010325    0.008525  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [58]:
dataset = df.values 
# astype 없으면 model.fit에서 unsupported objuect type float error 발생
x = dataset[:,:60].astype(float)

y = dataset[:,60]

e = LabelEncoder()
y = e.fit_transform(y)
y = y.reshape(-1,1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)
print("x_train.shape =", x_train.shape)
print("x_test.shape =", x_test.shape)
print("y_train.shape =", y_train.shape)
print("y_test.shape =", y_test.shape)
print(y_test[0:5])
      
model = Sequential()
model.add(Dense(100, input_dim=60, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# 모델 학습과정 설정 
model.compile(loss='binary_crossentropy', optimizer=optimizers.Adam(lr=0.01), metrics=['accuracy'])

# 모델 학습시키기
model.fit(x,y, epochs=40, batch_size=10)
model.summary()
#모델 평가하기
score = model.evaluate(x_test,y_test)

print("%s : %.4f%%" %(model.metrics_names[1], score[1]*100))

x_train.shape = (166, 60)
x_test.shape = (42, 60)
y_train.shape = (166, 1)
y_test.shape = (42, 1)
[[1]
 [1]
 [1]
 [1]
 [0]]
Epoch 1/40
21/21 [==============================] - 0s 474us/step - loss: 0.6779 - accuracy: 0.5817
Epoch 2/40
21/21 [==============================] - 0s 475us/step - loss: 0.6042 - accuracy: 0.6731
Epoch 3/40
21/21 [==============================] - 0s 475us/step - loss: 0.5086 - accuracy: 0.7500
Epoch 4/40
21/21 [==============================] - 0s 475us/step - loss: 0.4885 - accuracy: 0.7500
Epoch 5/40
21/21 [==============================] - 0s 475us/step - loss: 0.4432 - accuracy: 0.8029
Epoch 6/40
21/21 [==============================] - 0s 570us/step - loss: 0.4453 - accuracy: 0.7596
Epoch 7/40
21/21 [==============================] - 0s 570us/step - loss: 0.3935 - accuracy: 0.8077
Epoch 8/40
21/21 [==============================] - 0s 522us/step - loss: 0.3987 - accuracy: 0.7885
Epoch 9/40
21/21 [==============================] - 0s 617us/step - loss: 0.

In [89]:
##############################
# 훈련 검증셋 연습
################################
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras import optimizers # lr 조정할때 쓰임
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
np.random.seed(0)
tf.random.set_seed(0)

df = pd.read_csv('sonar.csv', header=None)

dataset = df.values 
# astype 없으면 model.fit에서 unsupported objuect type float error 발생
x = dataset[:,:60].astype(float)
y = dataset[:,60]

e = LabelEncoder()
y = e.fit_transform(y)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=0)

model = Sequential()
model.add(Dense(40, input_dim=60, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

print("x_train.shape =", x_train.shape)
print("x_test.shape =", x_test.shape)
print("y_train.shape =", y_train.shape)
print("y_test.shape =", y_test.shape)
print(y_test[0:5])

# 모델 학습과정 설정 
model.compile(loss='binary_crossentropy', optimizer=optimizers.Adam(lr=0.01), metrics=['accuracy'])

model.fit(x_train,y_train, epochs=50, batch_size=10)
score = model.evaluate(x_train,y_train)
print("%s : %.4f%%" %(model.metrics_names[1], score[1]*100))

score1 = model.evaluate(x_test,y_test)
print("%s : %.4f%%" %(model.metrics_names[1], score1[1]*100))

x_train.shape = (145, 60)
x_test.shape = (63, 60)
y_train.shape = (145,)
y_test.shape = (63,)
[1 1 1 1 0]
Epoch 1/50
15/15 [==============================] - 0s 530us/step - loss: 0.6872 - accuracy: 0.5586
Epoch 2/50
15/15 [==============================] - 0s 532us/step - loss: 0.6174 - accuracy: 0.6759
Epoch 3/50
15/15 [==============================] - 0s 532us/step - loss: 0.5411 - accuracy: 0.7310
Epoch 4/50
15/15 [==============================] - 0s 532us/step - loss: 0.4852 - accuracy: 0.7448
Epoch 5/50
15/15 [==============================] - 0s 532us/step - loss: 0.4505 - accuracy: 0.7724
Epoch 6/50
15/15 [==============================] - 0s 532us/step - loss: 0.5057 - accuracy: 0.7448
Epoch 7/50
15/15 [==============================] - 0s 532us/step - loss: 0.5161 - accuracy: 0.7310
Epoch 8/50
15/15 [==============================] - 0s 532us/step - loss: 0.5253 - accuracy: 0.7448
Epoch 9/50
15/15 [==============================] - 0s 665us/step - loss: 0.4203 - accuracy: 0

In [3]:
##############################
# 아이리스 훈련 검증셋
################################
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras import optimizers # lr 조정할때 쓰임
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from tensorflow import keras

np.random.seed(0)
tf.random.set_seed(0)

df = pd.read_csv('iris.csv', names = ['sepal_length','sepal_width','petal_length','petal_width','species'])
df = pd.DataFrame(df)

dataset = df.values
X = dataset[:,:-1].astype(float)
Y_obj = dataset[:,4]

#문자열을 숫자로 변환 (3품종을 1,2,3 으로 변환 하고 keras.utils.to_categorical로 [0,0,1] or [ 0,1,0] or [1,0,0] 으로 바꿈
# 그래서 sotfmax는 각 데이터의 합이 1로 만들어서 원핫인코딩이라고함 (가장 큰수를 1로 함)

e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)
Y_encoded = tf.keras.utils.to_categorical(Y)

model = Sequential()
model.add(Dense(16, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))

x_train, x_test, y_train, y_test = train_test_split(X, Y_encoded, test_size = 0.3, random_state=0)

#test_size: 테스트 셋 구성의 비율을 나타냅니다. 
#train_size의 옵션과 반대 관계에 있는 옵션 값이며, 주로 test_size를 지정해 줍니다. 
#0.2는 전체 데이터 셋의 20%를 test (validation) 셋으로 지정하겠다는 의미입니다. 
#default 값은 0.25 입니다.
#shuffle: default=True 입니다. split을 해주기 이전에 섞을건지 여부입니다. 보통은 default 값으로 놔둡니다.
#stratify: default=None 입니다. classification을 다룰 때 매우 중요한 옵션값입니다. 
#stratify 값을 target으로 지정해주면 각각의 class 비율(ratio)을 train / validation에 유지해 줍니다. 
#(한 쪽에 쏠려서 분배되는 것을 방지합니다) 
#random_state: 세트를 섞을 때 해당 int 값을 보고 섞으며, 하이퍼 파라미터를 튜닝시 이 값을 고정해두고 
#튜닝해야 매번 데이터셋이 변경되는 것을 방지할 수 있습니다.
    
print("x_train.shape =", x_train.shape)
print("x_test.shape =", x_test.shape)
print("y_train.shape =", y_train.shape)
print("y_test.shape =", y_test.shape)
print(y_test[0:5])

# 모델 학습과정 설정 
model.compile(loss='categorical_crossentropy', optimizer=optimizers.Adam(lr=0.001), metrics=['accuracy'])

model.fit(x_train,y_train, epochs=100, batch_size=10)

# 모델을 컴퓨터에 저장
model.save('my_model.h5')

# 모델을 컴퓨터에 불러오기
model = keras.models.load_model('my_model.h5')

print("%s : %.4f%%" %(model.metrics_names[1], model.evaluate(x_train,y_train)[1]*100))

print("%s : %.4f%%" %(model.metrics_names[1], model.evaluate(x_test,y_test)[1]*100))

x_train.shape = (105, 4)
x_test.shape = (45, 4)
y_train.shape = (105, 3)
y_test.shape = (45, 3)
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Epoch 1/100
11/11 [==============================] - 0s 452us/step - loss: 2.3305 - accuracy: 0.3714
Epoch 2/100
11/11 [==============================] - 0s 453us/step - loss: 2.0810 - accuracy: 0.3714
Epoch 3/100
11/11 [==============================] - 0s 363us/step - loss: 1.7911 - accuracy: 0.3810
Epoch 4/100
11/11 [==============================] - 0s 363us/step - loss: 1.5280 - accuracy: 0.5048
Epoch 5/100
11/11 [==============================] - 0s 362us/step - loss: 1.2800 - accuracy: 0.6762
Epoch 6/100
11/11 [==============================] - 0s 453us/step - loss: 1.0400 - accuracy: 0.6952
Epoch 7/100
11/11 [==============================] - 0s 544us/step - loss: 0.8745 - accuracy: 0.6952
Epoch 8/100
11/11 [==============================] - 0s 544us/step - loss: 0.7604 - accuracy: 0.6952
Epoch 9/100
11/11 [================

11/11 [==============================] - 0s 453us/step - loss: 0.2566 - accuracy: 0.9619
Epoch 80/100
11/11 [==============================] - 0s 544us/step - loss: 0.2544 - accuracy: 0.9619
Epoch 81/100
11/11 [==============================] - 0s 453us/step - loss: 0.2522 - accuracy: 0.9619
Epoch 82/100
11/11 [==============================] - 0s 454us/step - loss: 0.2483 - accuracy: 0.9619
Epoch 83/100
11/11 [==============================] - 0s 453us/step - loss: 0.2453 - accuracy: 0.9619
Epoch 84/100
11/11 [==============================] - 0s 363us/step - loss: 0.2433 - accuracy: 0.9619
Epoch 85/100
11/11 [==============================] - 0s 453us/step - loss: 0.2399 - accuracy: 0.9619
Epoch 86/100
11/11 [==============================] - 0s 363us/step - loss: 0.2376 - accuracy: 0.9619
Epoch 87/100
11/11 [==============================] - 0s 453us/step - loss: 0.2367 - accuracy: 0.9619
Epoch 88/100
11/11 [==============================] - 0s 363us/step - loss: 0.2348 - accuracy: 